userIDlist = ["max1","max2","max3","max4","max5"] # the computer will ...

while True:  # the computer will ...
    userID = input("Please choose an ID\n>>")  # the computer will ...
    if userID in userIDlist:  # the computer will ...
        print("ID taken!")  # the computer will ...
    else:
        userIDlist.append(userID)  # the computer will ...
        print("user ID saved!")  # the computer will ...
        break  # the computer will ...
